### ISSUE TITLE
NDK error when runs on Android 

### ISSUE THREAD

**Issue by dinhvantiep** [dttvn0010/mecab_dart#4]
Chào bạn, mình có gặp phải lỗi liên quan đến NDK khi chạy trên Android. Lỗi này xử lý thế nào bạn nhỉ ? Mình có thử tìm hiểu nhưng chưa giải quyết được.
Rất mong bạn giúp đỡ. 

 ![image](https://user-images.githubusercontent.com/5126923/125215006-ee217600-e2f4-11eb-9291-741e77138925.jpeg)

**Comment by dttvn0010** [comment]
Bạn thử dùng Android Studio gỡ package ndk 21.1.6352462 sau đó cài lại package ndk mới xem có hết lỗi không? Ngoài ra có thể dùng "flutter doctor" để kiểm tra môi trường phát triển có vấn đề gì setup thiếu không.

**Comment by dinhvantiep** [comment]
@dttvn0010 Mình thử cài package ndk 20.x thì chạy được rồi nhưng khi phân tích câu thì không trả về kết quả gì.
Chắc đó là vấn đề khác, mình close issue này nhé.

**Comment by dttvn0010** [comment]
[app-arm64-v8a-release.apk.zip](https://github.com/dttvn0010/mecab_dart/files/6831758/app-arm64-v8a-release.apk.zip)
Mình sử dụng ndk mới nhất (22.1.7171670) thì vẫn build được. Bạn kiểm tra xem đã thêm đường dẫn ndk ($ANDROID_HOME/ndk/<version>) vào đường dẫn hệ thống chưa?

**Comment by dttvn0010** [comment]
Nếu câu phân tích không trả về kết quả thì có thể lib đang bị lỗi với câu đó, bạn post nội dung câu đang test để mình kiểm tra.
